apiVersion: k6.io/v1alpha1
kind: TestRun
metadata:
  name: test-run
  namespace: observability
spec:
  parallelism: 2
  script:
    configMap:
      name: k6-tests
      file: test-run.js
  separate: false
  runner:
    securityContext:
      runAsUser: 1000
      runAsGroup: 1000
      runAsNonRoot: true
    resources:
      limits:
        cpu: 200m
        memory: 1000Mi
      requests:
        cpu: 100m
        memory: 500Mi
    env:
      - name: URL
        value: "https://example.com"
      - name: BASIC_AUTH_USER
        value: "user"
      - name: BASIC_AUTH_PASSWORD
        value: "password"